catalog:
  '@vue/compiler-core': https://pkg.pr.new/vuejs/vue-vapor/@vue/compiler-core@9f73dbf
  '@vue/compiler-dom': https://pkg.pr.new/vuejs/vue-vapor/@vue/compiler-dom@9f73dbf
  '@vue/compiler-vapor': https://pkg.pr.new/vuejs/vue-vapor/@vue/compiler-vapor@9f73dbf
  '@vue/runtime-vapor': https://pkg.pr.new/vuejs/vue-vapor/@vue/runtime-vapor@9f73dbf
  '@vue/shared': https://pkg.pr.new/vuejs/vue-vapor/@vue/shared@9f73dbf
  vue: https://pkg.pr.new/vuejs/vue-vapor/vue@9f73dbf
  '@babel/types': ^7.26.7
  '@babel/core': ^7.26.7
  '@babel/parser': ^7.26.7
  '@types/babel__core': ^7.20.5
packages:
  - packages/*
  - playground
