catalog:
  '@vue/compiler-core': https://pkg.pr.new/vuejs/vue-vapor/@vue/compiler-core@6d5bc43
  '@vue/compiler-dom': https://pkg.pr.new/vuejs/vue-vapor/@vue/compiler-dom@6d5bc43
  '@vue/compiler-vapor': https://pkg.pr.new/vuejs/vue-vapor/@vue/compiler-vapor@6d5bc43
  '@vue/runtime-vapor': https://pkg.pr.new/vuejs/vue-vapor/@vue/runtime-vapor@6d5bc43
  '@vue/shared': https://pkg.pr.new/vuejs/vue-vapor/@vue/shared@6d5bc43
  vue: https://pkg.pr.new/vuejs/vue-vapor/vue@6d5bc43
  '@babel/types': ^7.26.7
  '@babel/core': ^7.26.7
  '@babel/parser': ^7.26.7
  '@types/babel__core': ^7.20.5
packages:
  - packages/*
  - playground
