catalog:
  '@vue/compiler-dom': https://pkg.pr.new/@vue/compiler-dom@12927
  '@vue/compiler-vapor': https://pkg.pr.new/@vue/compiler-vapor@12893
  '@vue/shared': https://pkg.pr.new/@vue/shared@12927
  vue: https://pkg.pr.new/vue@12927
  '@babel/types': ^7.26.7
  '@babel/core': ^7.26.7
  '@babel/parser': ^7.26.7
  '@types/babel__core': ^7.20.5
packages:
  - packages/*
  - playground
