packages:
  - packages/*
  - playground
  - docs

defines:
  - &babel ^7.26.8
  - &vue-macros ^3.0.0-beta.7

catalog:
  '@babel/core': *babel
  '@babel/parser': *babel
  '@babel/plugin-syntax-jsx': ^7.25.9
  '@babel/plugin-transform-typescript': *babel
  '@babel/traverse': *babel
  '@babel/types': *babel
  '@types/babel__core': ^7.20.5

  '@nuxt/kit': ^3.16.0
  '@nuxt/schema': ^3.16.0

  '@vue/compiler-dom': https://pkg.pr.new/@vue/compiler-dom@b43f4f5
  '@vue/compiler-sfc': https://pkg.pr.new/@vue/compiler-sfc@b43f4f5
  '@vue/compiler-vapor': https://pkg.pr.new/@vue/compiler-vapor@b43f4f5
  '@vue/shared': https://pkg.pr.new/@vue/shared@b43f4f5

  '@vue-macros/common': *vue-macros
  '@vue-macros/reactivity-transform': *vue-macros
  '@vue-macros/test-utils': *vue-macros
  '@vue-macros/volar': *vue-macros

  '@types/hash-sum': ^1.0.2
  hash-sum: ^2.0.0
  ts-macro: ^0.1.25
  unplugin: ^1.16.1
  unplugin-utils: ^0.2.4
  vite: ^6.2.1
  vitest: ^3.0.8
  vue: https://pkg.pr.new/vue@b43f4f5
