packages:
  - packages/*
  - playground
  - docs

catalog:
  '@babel/core': ^7.26.8
  '@babel/parser': ^7.26.8
  '@babel/types': ^7.26.8
  '@nuxt/kit': ^3.16.0
  '@nuxt/schema': ^3.16.0
  '@types/babel__core': ^7.20.5
  '@vue/compiler-dom': https://pkg.pr.new/@vue/compiler-dom@eeab9c4
  '@vue/compiler-sfc': https://pkg.pr.new/@vue/compiler-sfc@eeab9c4
  '@vue/compiler-vapor': https://pkg.pr.new/@vue/compiler-vapor@eeab9c4
  '@vue/shared': https://pkg.pr.new/@vue/shared@eeab9c4
  ts-macro: ^0.1.25
  unplugin: ^1.16.1
  vite: ^6.2.1
  vitest: ^3.0.8
  vue: https://pkg.pr.new/vue@eeab9c4
